CREATE TABLE PlayerInfo(
   Player       VARCHAR(50) NOT NULL
  ,No           INTEGER 
  ,Class        VARCHAR(50)
  ,Pos          VARCHAR(50)
  ,Ht           VARCHAR(50)
  ,Wt           INTEGER 
  ,Hometown     VARCHAR(50)
  ,HS           VARCHAR(50)
  ,HS_Rk        VARCHAR(50)
  ,Summary      VARCHAR(50)
  ,PRIMARY KEY(Player,Hometown)
);
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Kyle Guy',5,'JR','G','6-2',175,'Indianapolis IN','Lawrence Central High School','32 (2016)','15.4 Pts 4.5 Reb 2.1 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('De''Andre Hunter',12,'SO','G','6-7',225,'Philadelphia PA','Friends'' Central School','74 (2016)','15.2 Pts 5.1 Reb 2.0 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Ty Jerome',11,'JR','G','6-5',195,'New Rochelle NY','Iona Preparatory School','46 (2016)','13.6 Pts 4.2 Reb 5.5 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Mamadi Diakite',25,'JR','F','6-9',228,'Conakry Guinea','Blue Ridge High School',NULL,'7.4 Pts 4.4 Reb 0.3 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Braxton Key',2,'JR','G','6-8',225,'Charlotte NC','Oak Hill Academy','56 (2016)','5.7 Pts 5.3 Reb 1.0 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Kihei Clark',0,'FR','G','5-9',155,'Woodland Hills CA','Taft Charter HS',NULL,'4.5 Pts 2.3 Reb 2.6 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Jay Huff',30,'SO','F','7-1',232,'Durham NC','Voyager Academy','61 (2016)','4.4 Pts 2.1 Reb 0.2 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Jack Salt',33,'SR','C','6-10',250,'Auckland New Zealand','Westlake HS',NULL,'3.7 Pts 3.7 Reb 0.4 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Kody Stattmann',23,'FR','G','6-7',187,'Bentley Park Australia',NULL,NULL,'1.7 Pts 0.6 Reb 0.1 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Marco Anthony',24,'SO','G','6-4',212,'San Antonio TX','Oliver Wendell Holmes High School',NULL,'1.2 Pts 0.5 Reb 0.5 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Grant Kersey',1,'FR','G',NULL,NULL,'Charlottesville VA',NULL,NULL,'1.3 Pts 0.2 Reb 0.1 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Austin Katstra',45,'SO','F','6-6',217,'Charlottesville VA','Albemarle High School',NULL,'0.9 Pts 0.5 Reb 0.3 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Jayden Nixon',10,'FR','G','6-3',189,'Charlottesville VA','Choate Rosemary Hall HS',NULL,'0.6 Pts 0.6 Reb 0.1 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Francesco Badocchi',1,'FR','F','6-7',205,'Milan Italy',NULL,NULL,'0.5 Pts 0.5 Reb 0.0 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Francisco Caffaro',22,'FR','C','7-0',233,'El Trebo Argentina','NBA Global Academy',NULL,NULL);
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Cameron Johnson',13,'SR','G','6-9',210,'Moon Township PA','Our Lady of the Sacred Heart HS',NULL,'16.9 Pts 5.8 Reb 2.4 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Coby White',2,'FR','G','6-5',185,'Goldsboro NC','Greenfield School','27 (2018)','16.1 Pts 3.5 Reb 4.1 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Luke Maye',32,'SR','F','6-8',240,'Huntersville NC','Hough HS',NULL,'14.9 Pts 10.4 Reb 2.3 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Nassir Little',5,'FR','F','6-6',220,'Orange Park FL','Orlando Christian Prep','3 (2018)','9.8 Pts 4.6 Reb 0.6 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Kenny Williams',24,'SR','G','6-4',185,'Midlothian VA','Bird HS','90 (2015)','8.6 Pts 3.9 Reb 3.5 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Garrison Brooks',15,'SO','F','6-9',230,'Lafayette AL','Auburn HS',NULL,'7.9 Pts 5.6 Reb 1.2 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Brandon Robinson',4,'JR','G','6-4',170,'Douglasville GA','Douglas County High School','65 (2016)','3.4 Pts 1.6 Reb 1.4 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Seventh Woods',0,'JR','G','6-2',185,'Columbia SC','Hammond School','40 (2016)','2.5 Pts 1.0 Reb 2.1 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Sterling Manley',21,'SO','F','6-11',235,'Pickerington OH','Pickerington Central',NULL,'3.5 Pts 2.9 Reb 0.2 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Rechon Black',1,'FR','G','6-7',185,'Concord NC','Cox Mill HS','64 (2018)','2.5 Pts 2.1 Reb 1.2 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Andrew Platek',3,'SO','G','6-3',200,'Guilderland NY','Northfield Mount Hermon School',NULL,'1.1 Pts 0.3 Reb 0.2 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Brandon Huffman',42,'SO','F','6-10',250,'Goldsboro NC','Word of God Christian Academy',NULL,'1.2 Pts 0.9 Reb 0.1 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('K.J. Smith',30,'SO','G','6-2',175,'Calabasas CA','IMG Academy',NULL,'1.0 Pts 0.1 Reb 0.3 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Walker Miller',22,'SO','F','6-10',230,'Greensboro NC','New Hampton School',NULL,'0.8 Pts 0.4 Reb 0.1 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Caleb Ellis',25,'JR','G','6-4',185,'Apex NC','Cary Christian School',NULL,'0.5 Pts 0.1 Reb 0.1 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Shea Rush',11,'JR','F','6-5',210,'Fairway KS','The Barstow School',NULL,'0.1 Pts 0.3 Reb 0.1 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Ryan McAdoo',35,'SO','F','6-5',201,'Boca Raton FL','Saint Andrew''s School',NULL,NULL);
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('R.J. Barrett',5,'FR','F','6-7',202,'Mississauga Canada','Monteverde Academy','1 (2018)','22.6 Pts 7.6 Reb 4.3 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Zion Williamson',1,'FR','F','6-7',285,'Spartanburg SC','Spartanburg Day School','4 (2018)','22.6 Pts 8.9 Reb 2.1 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Cam Reddish',2,'FR','F','6-8',218,'Norristown PA','Westtown School','2 (2018)','13.5 Pts 3.7 Reb 1.9 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Tre Jones',3,'FR','G','6-2',183,'Apple Valley MN','Apple Valley HS','13 (2018)','9.4 Pts 3.8 Reb 5.3 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Marques Bolden',20,'JR','C','6-11',250,'DeSoto TX','DeSoto High School','11 (2016)','5.3 Pts 4.5 Reb 0.5 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Alex O''Connell',15,'SO','G','6-6',183,'Roswell GA','Milton High School','69 (2017)','4.4 Pts 1.9 Reb 0.6 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Javin DeLaurier',12,'JR','F','6-10',234,'Shipman VA','St. Anne''s-Belfield School','35 (2016)','3.8 Pts 4.4 Reb 0.4 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Jack White',41,'JR','F','6-7',222,'Traralgon Australia','Australian Institute of Sport',NULL,'4.1 Pts 4.7 Reb 0.7 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Jordan Goldwire',14,'SO','G','6-2',181,'Norcross GA','Norcross High School',NULL,'0.9 Pts 0.8 Reb 0.7 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Antonio Vrankovic',30,'SR','C','7-0',269,'Zagreb Croatia','Pine Crest HS',NULL,'1.4 Pts 1.3 Reb 0.4 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Justin Robinson',50,'JR','F','6-10',202,'San Antonio TX','San Antonio Christian School High School',NULL,'1.2 Pts 0.5 Reb 0.1 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Brennan Besser',53,'SR','G','6-5',190,'Chicago IL','Latin School',NULL,'1.0 Pts 0.8 Reb 0.3 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Joey Baker',13,'FR','F','6-7',200,'Fayetteville NC','Trinity Christian School','37 (2018)','0.8 Pts 1.0 Reb 0.0 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Mike Buckmire',51,'SO','G','6-2',173,'Blue Bell PA','Germantown Friends School',NULL,'0.0 Pts 1.0 Reb 0.3 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Mfiondu Kabengele',25,'SO','F','6-10',250,'Burlington Canada','Don Bosco Preparatory High School',NULL,'13.2 Pts 5.9 Reb 0.3 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Terance Mann',14,'SR','G','6-7',215,'Lowell MA','Tilton School (NH)',NULL,'11.4 Pts 6.5 Reb 2.5 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Trent Forrest',3,'JR','G','6-4',210,'Chipley FL','Chipley High School','69 (2016)','9.3 Pts 4.5 Reb 3.7 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('M.J. Walker',23,'SO','G','6-5',213,'Jonesboro GA','Jonesboro High School','24 (2017)','7.5 Pts 2.2 Reb 1.6 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Christ Koumadje',21,'SR','C','7-4',268,'N''Djamena Chad','Montverde Academy',NULL,'6.6 Pts 5.6 Reb 0.2 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('David Nichols',11,'SR','G','6-1',185,'Chicago IL','Midwest Academy',NULL,'6.4 Pts 1.7 Reb 1.7 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('PJ Savoy',5,'SR','G','6-4',210,'Las Vegas NV','Las Vegas High School',NULL,'5.9 Pts 1.2 Reb 0.5 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Phil Cofer',0,'SR','F','6-8',230,'Fayetteville GA','Whitewater HS',NULL,'7.4 Pts 3.5 Reb 0.8 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Devin Vassell',24,'FR','G','6-6',180,'Suwnaee GA','Peachtree Ridge HS',NULL,'4.5 Pts 1.5 Reb 0.6 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Raiquan Gray',1,'FR','F','6-8',260,'Fort Lauderdale FL','Dillard HS',NULL,'3.9 Pts 2.3 Reb 0.8 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Anthony Polite',13,'FR','G','6-6',215,'Lugano Switzerland','Saint Andrew''s School',NULL,'2.7 Pts 1.6 Reb 0.6 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Wyatt Wilkes',31,'SO','F','6-8',220,'Orlando FL','Winter Park High School',NULL,'1.5 Pts 0.8 Reb 0.1 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Harrison Prieto',35,'SO','F','6-8',230,'Mandeville LA','St. Paul''s School',NULL,'0.9 Pts 0.9 Reb 0.0 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Justin Lindner',15,'JR','G','6-1',180,'Memphis TN','Christian Brothers High School',NULL,'0.3 Pts 0.3 Reb 0.7 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Will Miles',33,'SO','G','6-6',220,'Orlando FL','Trinity Preparatory School',NULL,'0.2 Pts 0.2 Reb 0.0 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Travis Light',20,'SO','G','6-5',175,'Vienna VA','Montverde Academy',NULL,'0.0 Pts 0.0 Reb 0.0 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Ty Hands',4,'FR','G','6-5',180,'Palm Beach Lakes FL','Palm Beach Lakes HS',NULL,NULL);
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Malik Osborne',10,'SO','F','6-9',215,'Matteson IL','Don Bosco Preparatory High School',NULL,NULL);
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Nickeil Alexander-Walker',4,'SO','G','6-5',205,'Toronto Canada','Hamilton Heights Christian Academy','33 (2017)','16.2 Pts 4.1 Reb 4.0 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Kerry Blackshear Jr.',24,'JR','F','6-10',250,'Orlando FL','Maynard Evans HS',NULL,'14.9 Pts 7.5 Reb 2.4 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Ahmed Hill',13,'SR','G','6-5',210,'Augusta GA','Aquinas HS','61 (2014)','13.1 Pts 3.9 Reb 1.3 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Justin Robinson',5,'SR','G','6-2',195,'Manassas VA','St. James School','95 (2015)','13.5 Pts 3.2 Reb 5.0 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Ty Outlaw',42,'SR','G','6-6',220,'Roxboro NC','Person County High School',NULL,'8.6 Pts 5.2 Reb 0.9 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Isaiah Wilkins',1,'FR','G','6-3',230,'Winston-Salem NC','Mount Tabor HS',NULL,'4.7 Pts 2.3 Reb 0.6 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Wabissa Bede',3,'SO','G','6-1',195,'North Andover MA','Cushing Academy','81 (2017)','3.8 Pts 2.5 Reb 2.3 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('P.J. Horne',14,'SO','F','6-5',230,'Tifton GA','Tift County High School',NULL,'3.3 Pts 2.2 Reb 0.3 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Jonathan Kabongo',10,'FR','G','6-4',195,'Toronto Canada',NULL,NULL,'1.5 Pts 0.6 Reb 0.2 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Brendan Palmer',11,'FR','G','6-3',190,'Lewisville NC',NULL,NULL,'0.0 Pts 0.0 Reb 0.0 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Landers Nolley II',21,'FR','G','6-7',230,'Fairburn GA','Langston Hughes HS','72 (2018)',NULL);
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Tyrece Radford',23,'FR','G','6-2',195,'Baton Rouge LA','McKinley HS',NULL,NULL);
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Jordan Nwora',33,'SO','F','6-7',225,'Buffalo NY','Canisius High School','73 (2017)','17.0 Pts 7.6 Reb 1.3 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Dwayne Sutton',24,'JR','F','6-5',215,'Louisville KY','DuPont Manual HS',NULL,'10.0 Pts 6.9 Reb 1.9 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Christen Cunningham',1,'SR','G','6-2',190,'Georgetown KY','Cordia High School',NULL,'10.1 Pts 2.2 Reb 4.8 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Steven Enoch',23,'JR','C','6-10',260,'Norwalk CT','St. Thomas More HS','62 (2015)','9.4 Pts 5.2 Reb 0.2 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Malik Williams',5,'SO','F','6-11',245,'Fort Wayne IN','R. Nelson Snider High School','25 (2017)','7.7 Pts 6.1 Reb 0.3 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Ryan McMahon',30,'JR','G','6-0',180,'Sarasota FL','Cardinal Mooney HS',NULL,'7.2 Pts 1.1 Reb 1.8 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Darius Perry',2,'SO','G','6-2',195,'Marietta GA','Joseph Wheeler High School','71 (2017)','5.4 Pts 1.4 Reb 1.5 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('V.J. King',13,'JR','F','6-6',215,'Cleveland OH','Paul VI Catholic High School','25 (2016)','3.9 Pts 3.0 Reb 0.6 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Khwan Fore',4,'SR','G','6-0',185,'Huntsville AL','Lee HS',NULL,'3.3 Pts 1.3 Reb 1.2 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Akoy Agau',0,'SR','F','6-8',240,'Juba South Sudan','Omaha Central','88 (2013)','1.6 Pts 2.0 Reb 0.2 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Jacob Redding',12,'SO','G','6-0',180,'Fort Wayne IN','Carroll High School',NULL,'0.9 Pts 0.4 Reb 0.0 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Jo Griffin',3,'SO','G','6-1',200,'Lagrange KY','South Oldham High School',NULL,'0.4 Pts 0.0 Reb 0.1 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Wyatt Battaile',10,'FR','G','6-4',195,'Pikeville KY','Pikeville HS',NULL,'0.0 Pts 0.3 Reb 0.1 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Will Rainey',14,'SR','G','6-3',180,'Louisville KY',NULL,NULL,NULL);
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Tyus Battle',25,'JR','G','6-6',205,'Edison NJ','Gill ST. Bernard''s School','31 (2016)','17.2 Pts 3.3 Reb 2.5 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Elijah Hughes',33,'JR','F','6-6',215,'Beacon NY','John F. Kennedy Catholic High School',NULL,'13.7 Pts 4.3 Reb 1.5 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Oshae Brissett',11,'SO','F','6-8',210,'Mississauga Canada','Athlete Institute Prep',NULL,'12.4 Pts 7.5 Reb 1.8 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Frank Howard',23,'SR','G','6-5',205,'Suitland MD','Paul IV HS','79 (2015)','8.9 Pts 2.0 Reb 2.9 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Buddy Boeheim',35,'FR','G','6-5',188,'Fayetteville NY','Brewster Academy',NULL,'6.8 Pts 1.6 Reb 1.0 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Paschal Chukwu',13,'SR','C','7-2',228,'Westport CT','Fairfield Prep','66 (2014)','4.4 Pts 5.4 Reb 0.2 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Marek Dolezaj',21,'SO','F','6-10',180,'Bratislava Slovakia','MBK Karlovka Bratislava',NULL,'4.1 Pts 3.5 Reb 1.6 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Jalen Carey',5,'FR','G','6-3',168,'Harlem NJ','Immaculate Conception HS','52 (2018)','3.5 Pts 1.6 Reb 1.0 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Bourama Sidibe',34,'SO','F','6-10',205,'Bamako Mali','Saint Benedict''s Preparatory School',NULL,'1.9 Pts 2.7 Reb 0.2 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Robert Braswell',20,'FR','F','6-9',184,'Jacksonville FL',NULL,NULL,'2.2 Pts 0.8 Reb 0.4 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Ky Feldman',54,'SR','G','5-10',155,'Agoura Hills CA','Agoura HS',NULL,'0.4 Pts 0.3 Reb 0.0 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Adrian Autry',0,'SR','G','6-0',185,'Jamesville NY','Jamesville-DeWitt HS',NULL,'0.0 Pts 0.1 Reb 0.1 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Antonio Balandi',4,'SR','F','6-6',210,'Portland OR','International School of Ouagadougou',NULL,'0.0 Pts 0.3 Reb 0.0 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Ray Featherston',32,'JR','G','5-8',150,'Westport CT','Fairfield College Preparatory School',NULL,'0.0 Pts 0.0 Reb 0.3 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Brendan Paul',12,'FR','G','6-2',177,'Shaker Heights OH','Brewster Academy',NULL,'0.0 Pts 0.0 Reb 0.0 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Howard Washington',10,'SO','G','6-3',180,'Buffalo NY','Athlete Institute Prep',NULL,'0.0 Pts 1.3 Reb 0.3 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Shaun Belbey',24,'SR','G','5-10',165,'Brick NJ','Uniondale HS',NULL,NULL);
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Torin Dorn',2,'SR','G','6-5',210,'Charlotte NC','Vance',NULL,'14.0 Pts 7.2 Reb 1.3 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('C.J. Bryce',13,'JR','G','6-5',195,'Charlotte NC','North Mecklenburg HS',NULL,'11.6 Pts 4.6 Reb 1.8 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Markell Johnson',11,'JR','G','6-1',175,'Cleveland OH','East Technical High School','88 (2016)','12.6 Pts 2.6 Reb 4.2 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Devon Daniels',24,'SO','G','6-5',200,'Battle Creek MI','Prolific Prep',NULL,'9.3 Pts 4.4 Reb 1.6 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Braxton Beverly',10,'SO','G','6-0',180,'Hazard KY','Hargrave Military Academy',NULL,'9.4 Pts 1.7 Reb 2.5 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('DJ Funderburk',0,'SO','F','6-10',210,'Cleveland OH','Hargrave Military Academy','66 (2016)','8.8 Pts 4.2 Reb 0.4 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Jericole Hellems',4,'FR','F','6-7',198,'St. Louis MO','Chaminade HS',NULL,'5.3 Pts 2.5 Reb 0.7 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Wyatt Walker',33,'SR','F','6-9',240,'Jacksonville FL','Providence School',NULL,'4.8 Pts 4.5 Reb 0.8 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Eric Lockett',5,'SR','G','6-5',193,'Warner Robins GA','Whitefield Academy',NULL,'4.4 Pts 2.9 Reb 1.2 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Blake Harris',55,'SO','G','6-3',190,'Chapel Hill NC','Word of God Christian Academy',NULL,'3.1 Pts 1.3 Reb 1.5 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Ian Steere',21,'FR','F','6-9',261,'Sanford NC','Northwood Temple Academy',NULL,'4.0 Pts 4.0 Reb 1.0 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Manny Bates',12,'FR','F','6-11',221,'Fayetteville NC','Northwood Temple Academy','98 (2018)',NULL);
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Sacha Killeya-Jones',1,'JR','F','6-11',220,'Chapel Hill NC','Virginia Episcopal School','21 (2016)',NULL);
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Marcquise Reed',2,'SR','G','6-3',188,'Landover MD','Capital Christian',NULL,'19.4 Pts 5.5 Reb 3.0 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Elijah Thomas',14,'SR','F','6-9',245,'Dallas TX','Lancaster HS','40 (2015)','13.0 Pts 7.8 Reb 1.4 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Shelton Mitchell',4,'SR','G','6-4',200,'Waxhaw NC','Oak Hill Academy','80 (2014)','11.5 Pts 2.7 Reb 3.0 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Aamir Simms',25,'SO','F','6-7',248,'Palmyra VA','Blue Ridge High School',NULL,'8.1 Pts 4.6 Reb 1.0 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('David Skara',24,'SR','F','6-8',213,'Zadar Croatia','Ekonomska Skola Zadar',NULL,'7.6 Pts 4.2 Reb 1.5 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Clyde Trapp',0,'SO','G','6-4',196,'Eastover SC','Lower Richland High School',NULL,'6.0 Pts 3.4 Reb 1.6 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('John Newman III',15,'FR','G','6-5',197,'Greensboro NC','Greensboro Day School',NULL,'2.1 Pts 1.7 Reb 0.4 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Javan White',35,'SR','F','6-10',227,'Ames IA','Ames HS',NULL,'2.0 Pts 2.0 Reb 0.2 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Tyson Hunter',5,'FR','F','6-8',204,'Monroe NC','Piedmont HS',NULL,'1.6 Pts 1.0 Reb 0.4 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Trey Jemison',55,'FR','C','7-0',254,'Birmingham AL','Hoover HS',NULL,'0.4 Pts 0.8 Reb 0.1 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Lyles Davis',3,'SR','G','5-11',166,'Charleston SC','James Island Charter HS',NULL,'0.4 Pts 0.1 Reb 0.1 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Parker Fox',10,'FR','G','6-6',190,'Reno NV','Oconee HS',NULL,'0.6 Pts 0.0 Reb 0.0 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Jonathan Baehre',1,'SO','F','6-10',214,'Hessen Germany','Wilkinson County High School',NULL,NULL);
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Malik William',20,'SO','F','6-8',226,'Orlando FL','The First Academy',NULL,NULL);
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Jose Alvarado',10,'SO','G','6-0',176,'Brooklyn NY','Christ The King Regional High School',NULL,'12.5 Pts 3.9 Reb 3.4 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('James Banks III',1,'JR','F','6-9',243,'Decatur GA',NULL,NULL,'10.5 Pts 7.8 Reb 1.4 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Michael Devoe',0,'FR','G','6-4',188,'Orlando FL','Montverde Academy','49 (2018)','9.7 Pts 3.3 Reb 2.5 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Moses Wright',5,'SO','F','6-9',221,'Raleigh NC','Enloe High School',NULL,'6.7 Pts 3.8 Reb 0.8 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Abdoulaye Gueye',34,'SR','F','6-9',217,'Dakar Senegal','Central Park Christian HS',NULL,'6.6 Pts 3.7 Reb 0.8 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Brandon Alston',4,'SR','G','6-5',203,'Vienna VA','Herndon HS',NULL,'7.0 Pts 1.7 Reb 1.0 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Curtis Haywood II',13,'SO','G','6-5',202,'Oklahoma City OK','Brewster Academy',NULL,'5.6 Pts 2.7 Reb 2.0 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Khalid Moore',12,'FR','F','6-6',200,'Briarwood NY','Archbishop Molloy HS',NULL,'4.2 Pts 1.5 Reb 1.2 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Evan Cole',3,'SO','F','6-9',217,'Cumming GA','South Forsyth High School',NULL,'4.1 Pts 2.4 Reb 0.6 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Kristian Sjolund',35,'FR','F','6-7',200,'Kongsberg Norway','Obra D. Tompkins HS',NULL,'3.0 Pts 1.0 Reb 0.2 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Shembari Phillips',2,'JR','G','6-3',202,'Atlanta GA','Wheeler HS',NULL,'2.1 Pts 1.1 Reb 0.8 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Sylvester Ogbonda',24,'JR','F','6-10',237,'Port Harcourt Nigeria','National Christian Academy',NULL,'1.8 Pts 1.7 Reb 0.4 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Evan Jester',11,'SO','F','6-6',191,'Riverdale GA','Sandy Creek High School',NULL,'0.0 Pts 0.5 Reb 0.0 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Shaheed Medlock',45,'JR','G','6-5',196,'Waycross GA','Ware County High School',NULL,'0.0 Pts 0.0 Reb 0.0 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Malachi Rice',55,'SO','G','6-0',186,'Indianapolis IN','Brebeuf Jesuit Preparatory School',NULL,'0.0 Pts 0.0 Reb 0.0 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Avi Schafer',32,'SO','C','6-8',235,'Osaka Japan','Brewster Academy',NULL,'0.0 Pts 1.0 Reb 0.0 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Ky Bowman',0,'JR','G','6-1',188,'Havelock NC','Havelock High School',NULL,'19.0 Pts 7.5 Reb 4.0 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Nik Popovic',21,'JR','F','6-11',253,'Banja Luka Bosnia and Herzegovina','Sagemont School',NULL,'14.5 Pts 7.2 Reb 1.1 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Jordan Chatman',25,'SR','G','6-5',210,'Vancouver WA','Union HS',NULL,'13.2 Pts 2.2 Reb 2.0 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Wynston Tabbs',5,'FR','G','6-2',193,'Leonardstown MD','St. Mary''s Ryken HS',NULL,'13.9 Pts 3.9 Reb 2.7 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Jairus Hamilton',1,'FR','F','6-8',234,'Charlotte NC','Cannon School','69 (2018)','5.6 Pts 4.0 Reb 0.8 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Chris Herren Jr.',4,'FR','G','6-3',174,'Portsmouth RI','Tabor Academy',NULL,'4.2 Pts 1.7 Reb 0.6 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Steffon Mitchell',41,'SO','F','6-8',220,'Shakopee MN','Shakopee High School',NULL,'4.6 Pts 7.9 Reb 2.3 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Jared Hamilton',3,'JR','G','6-4',203,'Charlotte NC','St. Frances Academy',NULL,'6.0 Pts 2.1 Reb 0.5 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Johncarlos Reyes',12,'JR','F','6-10',214,'Lawrenceville GA','Kingdom Christian Academy',NULL,'1.9 Pts 1.0 Reb 0.0 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Lucas Kraljevic',13,'SO','F','6-10',228,'Domzale Slovenia','Don Bosco Preparatory High School',NULL,'1.1 Pts 1.2 Reb 0.4 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Vin Baker Jr.',11,'SO','F','6-7',184,'Old Saybrook CT','Old Saybrook Senior High School',NULL,'1.3 Pts 1.0 Reb 0.3 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Avery Wilson',2,'SO','G','6-3',219,'Forest Park GA','Forest Park High School',NULL,'0.3 Pts 0.5 Reb 0.5 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Matt DiLuccio',22,'JR','G','5-11',180,'Rockville Centre NY','South Side High School',NULL,'0.0 Pts 0.0 Reb 0.0 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Gordon Gehan',20,'SR','G','6-5',220,'Dallas TX','Episcopal School of Dallas',NULL,'0.0 Pts 0.0 Reb 0.0 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Ervins Meznieks',10,'SR','F','6-7',228,'Riga Latvia','Rigas Teikas',NULL,'0.0 Pts 0.3 Reb 0.0 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Mac Bohuny',55,'SO','G','6-4',175,'Ridgewood NJ','Stony Brook School',NULL,NULL);
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Sam Holtze',30,'SO','G','5-10',150,'Manhattan Beach CA','Notre Dame HS',NULL,NULL);
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Will Jackowitz',24,'SO','F','6-8',205,'Wellesley MA','Wellesley High School',NULL,NULL);
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Chris Lykes',0,'SO','G','5-7',157,'Mitchellville MD','Gonzaga College High School','65 (2017)','16.2 Pts 2.7 Reb 3.2 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Anthony Lawrence Jr.',3,'SR','G','6-7',207,'St. Petersburg FL','Lakewood Senior HS',NULL,'12.6 Pts 6.7 Reb 3.1 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Zach Johnson',5,'SR','G','6-2',192,'Miami FL','Norland HS',NULL,'11.8 Pts 2.8 Reb 2.4 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Dejan Vasiljevic',1,'JR','G','6-3',184,'Melbourne Australia','Australian Institute of Sport',NULL,'11.8 Pts 4.5 Reb 1.2 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Ebuka Izundu',15,'SR','C','6-10',232,'Charlotte NC','Victory Christian Center School (NC)',NULL,'10.9 Pts 8.3 Reb 1.0 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Sam Waardenburg',21,'SO','F','6-10',216,'Aukland New Zealand','Rangitoto School',NULL,'5.3 Pts 3.5 Reb 1.2 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Anthony Mack',13,'FR','G','6-6',214,'Las Vegas NV',NULL,NULL,'2.6 Pts 1.0 Reb 0.7 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Deng Gak',22,'FR','F','6-10',211,'Sydney Australia','Blair Academy',NULL,'2.5 Pts 4.1 Reb 0.6 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Willie Herenton',2,'SO','G','6-1',178,'Lincolnshire IL','Stevenson HS',NULL,'0.9 Pts 0.1 Reb 0.0 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Dominic Proctor',10,'SO','G','6-6',180,'Las Vegas NV','Bishop Gorman HS',NULL,'0.0 Pts 0.0 Reb 0.0 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Dewan Hernandez',20,NULL,'F','6-11',235,'Miami FL','Miami Norland High School','27 (2016)',NULL);
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Kameron McGusty',23,'JR','G','6-5',192,'Katy TX','Seven Lakes High School','38 (2016)',NULL);
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Rodney Miller Jr.',14,NULL,'C','7-0',255,'Laurelton NY','Oak Hill Academy',NULL,NULL);
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Brandon Childress',0,'JR','G','6-0',190,'Winston-salem NC','Wesleyan Christian Academy',NULL,'14.7 Pts 3.8 Reb 4.0 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Jaylen Hoard',10,'FR','F','6-8',215,'Carnon France','Wesleyan Christian Academy','19 (2018)','13.1 Pts 7.6 Reb 1.5 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Chaundee Brown',23,'SO','G','6-5',215,'Orlando FL','Dr. Phillips High School','34 (2017)','11.9 Pts 4.9 Reb 1.2 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Sharone Wright Jr',2,'FR','G','6-5',180,'Florence SC','Legacy Early College HS',NULL,'7.1 Pts 2.4 Reb 1.0 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Isaiah Mucius',1,'FR','F','6-8',190,'East Patchogue NY','Brewster Academy','92 (2018)','6.5 Pts 3.7 Reb 0.7 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Olivier Sarr',30,'SO','C','7-0',235,'Toulouse France','INSEP',NULL,'6.2 Pts 5.5 Reb 0.5 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Torry Johnson',4,'SR','G','6-3',170,'Chicago IL','Morgan Park HS',NULL,'5.9 Pts 1.8 Reb 1.4 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Ikenna Smart',35,'SR','F','6-10',245,'Umuahia Nigeria','New Garden Friends School',NULL,'2.2 Pts 3.3 Reb 0.1 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Michael Wynn',20,'FR','G','6-6',200,'Albany NY',NULL,NULL,'1.9 Pts 0.9 Reb 0.1 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Sunday Okeke',34,'SO','F','6-8',245,'Lagos Nigeria','Greens Farms Academy',NULL,'1.2 Pts 2.1 Reb 0.2 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Aaron Spivey',41,'SR','G','6-2',175,'Rocky Mount NC','Nash Central high School',NULL,'0.8 Pts 0.3 Reb 0.3 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Anthony Bilas',40,'SR','G','6-2',160,'Charlotte NC','Charlotte Latin HIgh School',NULL,'0.5 Pts 0.1 Reb 0.0 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Jamie Lewis',25,'FR','G','6-3',190,'Atlanta GA','Westlake HS',NULL,'0.4 Pts 0.6 Reb 0.3 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Blake Buchanan',31,'FR','F','6-5',195,'Durham NC','Voyager Academy',NULL,'0.2 Pts 0.6 Reb 0.1 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Miles Lester',55,'SO','G','6-0',170,'Wichita KS','Wilbraham & Monson Academy',NULL,NULL);
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Andrien White',13,'SR','G','6-3',190,'Richmond VA','Quality Education Academy',NULL,NULL);
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('John Mooney',33,'JR','F','6-9',242,'Orlando FL','Lake Brantley High School',NULL,'14.1 Pts 11.2 Reb 1.3 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Temple Gibbs',10,'JR','G','6-3',194,'Scotch Plains NJ','Seton Hall Preparatory School','78 (2016)','13.4 Pts 1.9 Reb 3.4 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('D.J. Harvey',5,'SO','G','6-6',225,'Bowie MD','DeMatha Catholic High School','43 (2017)','10.7 Pts 4.2 Reb 0.7 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Prentiss Hubb',3,'FR','G','6-3',167,'Upper Marlboro MD',NULL,'92 (2018)','8.1 Pts 3.1 Reb 4.0 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Nate Laszewski',14,'FR','F','6-10',200,'Jupiter FL',NULL,'61 (2018)','6.9 Pts 3.9 Reb 0.2 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Dane Goodwin',23,'FR','G','6-6',203,'Upper Arlington OH','Upper Arlington HS',NULL,'6.4 Pts 3.2 Reb 1.1 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Juwan Durham',11,'JR','F','6-11',223,'Tampa FL','Tampa Preparatory School','50 (2016)','5.7 Pts 3.9 Reb 0.5 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Rex Pflueger',0,'SR','G','6-6',209,'Dana Point CA','Mater Dei HS',NULL,'8.1 Pts 4.7 Reb 4.3 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Nikola Djogo',13,'JR','G','6-7',217,'Hamilton Canada','Athlete Institute Prep',NULL,'2.7 Pts 2.1 Reb 0.8 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Robby Carmody',24,'FR','G','6-4',204,'Mars PA','Mars Area HS','92 (2018)','3.7 Pts 1.7 Reb 0.2 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Elijah Burns',12,'SR','F','6-8',237,'Troy NY','Blair Academy',NULL,'5.3 Pts 3.8 Reb 0.3 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Chris Doherty',15,'FR','F','6-8',225,'Marlborough MA','Marlborough HS',NULL,'0.8 Pts 0.9 Reb 0.1 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Liam Nelligan',25,'SR','G','6-5',198,'La Grange Park IL','Benet Academy',NULL,'0.0 Pts 0.1 Reb 0.0 Ast');
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Xavier Johnson',1,'FR','G','6-3',190,'Woodbridge VA','Bishop O''Connell HS','15.5 Pts 3.9 Reb 4.5 Ast',NULL);
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Jared Wilson-Frame',4,'SR','G','6-5',220,'Hartford CT','Believe Prep','12.7 Pts 5.0 Reb 1.4 Ast',NULL);
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Trey McGowens',2,'FR','G','6-3',185,'Pendleton SC','Hargrave Military Academy','11.6 Pts 3.2 Reb 1.7 Ast',NULL);
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Au''Diese Toney',5,'FR','G','6-6',210,'Huntsville AL','Trinity Christian Academy','7.5 Pts 5.6 Reb 0.5 Ast',NULL);
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Terrell Brown',21,'SO','F','6-10',230,'Providence RI','Tilton School','5.7 Pts 4.5 Reb 0.2 Ast',NULL);
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Malik Ellison',3,'JR','G','6-6',215,'Voorhees NJ','Life Center Academy (NJ)','5.8 Pts 3.8 Reb 1.2 Ast',NULL);
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Sidy N''Dir',11,'SR','G','6-3',180,'Cosne France','West Oak Academy','5.9 Pts 2.0 Reb 1.9 Ast',NULL);
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Kene Chukwuka',15,'JR','F','6-9',225,'Stockholm Sweden','Soderslatts Gymnasiet','3.9 Pts 3.5 Reb 0.4 Ast',NULL);
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Khameron Davis',13,'SO','G','6-4',200,'Denver CO','Forest Trail Academy','2.5 Pts 2.2 Reb 0.3 Ast',NULL);
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Shamiel Stevenson',0,'SO','G','6-6',245,'Toronto Canada','Hillcrest Academy','3.8 Pts 1.8 Reb 0.3 Ast',NULL);
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Samson George',24,'SO','F','6-7',210,'Minna Nigeria','First Love Christian Academy','1.4 Pts 1.6 Reb 0.0 Ast',NULL);
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Peace Ilegomah',42,'SO','C','6-9',240,'Benin City Nigeria','Montverde Academy','0.9 Pts 1.0 Reb 0.1 Ast',NULL);
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Anthony Starzynski',22,'JR','G','6-3',190,'Pittsburgh PA','Baldwin High School','1.0 Pts 0.3 Reb 0.0 Ast',NULL);
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Onyebuchi Ezeakudo',31,'FR','G','5-11',180,'Fort Wayne IN','Homestead HS','0.0 Pts 0.5 Reb 1.5 Ast',NULL);
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Joe Mascaro',12,'SR','G','5-10',170,'Pittsburgh PA','Bethel Park High School','0.0 Pts 0.3 Reb 0.0 Ast',NULL);
INSERT INTO PlayerInfo(Player,No,Class,Pos,Ht,Wt,Hometown,HS,HS_Rk,Summary) VALUES ('Curtis Aiken Jr.',14,'FR','G','6-1',180,'Pittsburgh PA','North Allegheny HS',NULL,NULL);
